# action.yml
name: 'ScanDependencies'
description: 'Scans ur dependencies'
inputs:
  workingdir:  
    description: 'Which directory should get scanned'
    required: false
    default: '.'
outputs:
  time: # id of output
    logs: 'The report logs'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/schadow98/schadow-security-scanner:latest'
  args:
    - ${{ inputs.workingdir }}
