name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    env:
      LOWERCASE_REPO_NAME: schadow98/schadow-security-scanner
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run unittest
    #   run: |
    #     python tests/unittest 
    # 
    # - name: Run end2end-test
    #   run: |
    #     python tests/unittest 

    - name: Build CLI Tool
      run: |
        pyinstaller --onefile --add-data "src:." --distpath ./dist --name SecurityScannerSchadow ./src/SecurityScanner.py
        cp ./securityScannerConfig.json ./dist/securityScannerConfig.json

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SecurityScanner
        path: dist/


