name: Code Scanner

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: SecurityScanner
        path: ./dist

    - name: Run Security Scanner
      run: |
        ./dist/SecurityScannerSchadow --config ./dist/securityScannerConfig.json --target .

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: logsSecurityScan
        path: logs/